export enum BrazilStates {
  Acre = 'AC',
  Alagoas = 'AL',
  Amapa = 'AP',
  Amazonas = 'AM',
  Bahia = 'BA',
  Ceara = 'CE',
  DistritoFederal = 'DF',
  EspiritoSanto = 'ES',
  Goias = 'GO',
  Maranhao = 'MA',
  MatoGrosso = 'MT',
  MatoGrossoDoSul = 'MS',
  MinasGerais = 'MG',
  Para = 'PA',
  Paraiba = 'PB',
  Parana = 'PR',
  Pernambuco = 'PE',
  Piaui = 'PI',
  RioDeJaneiro = 'RJ',
  RioGrandeDoNorte = 'RN',
  RioGrandeDoSul = 'RS',
  Rondonia = 'RO',
  Roraima = 'RR',
  SantaCatarina = 'SC',
  SaoPaulo = 'SP',
  Sergipe = 'SE',
  Tocantins = 'TO'
}

export const BrazilStatesRecord: Record<BrazilStates, string> = {
  [BrazilStates.Acre]: 'Acre',
  [BrazilStates.Alagoas]: 'Alagoas',
  [BrazilStates.Amapa]: 'Amapa',
  [BrazilStates.Amazonas]: 'Amazonas',
  [BrazilStates.Bahia]: 'Bahia',
  [BrazilStates.Ceara]: 'Ceara',
  [BrazilStates.DistritoFederal]: 'Distrito Federal',
  [BrazilStates.EspiritoSanto]: 'Espirito Santo',
  [BrazilStates.Goias]: 'Goias',
  [BrazilStates.Maranhao]: 'Maranhao',
  [BrazilStates.MatoGrosso]: 'Mato Grosso',
  [BrazilStates.MatoGrossoDoSul]: 'Mato Grosso do Sul',
  [BrazilStates.MinasGerais]: 'Minas Gerais',
  [BrazilStates.Para]: 'Para',
  [BrazilStates.Paraiba]: 'Paraiba',
  [BrazilStates.Parana]: 'Parana',
  [BrazilStates.Pernambuco]: 'Pernambuco',
  [BrazilStates.Piaui]: 'Piaui',
  [BrazilStates.RioDeJaneiro]: 'Rio de Janeiro',
  [BrazilStates.RioGrandeDoNorte]: 'Rio Grande do Norte',
  [BrazilStates.RioGrandeDoSul]: 'Rio Grande do Sul',
  [BrazilStates.Rondonia]: 'Rondonia',
  [BrazilStates.Roraima]: 'Roraima',
  [BrazilStates.SantaCatarina]: 'Santa Catarina',
  [BrazilStates.SaoPaulo]: 'Sao Paulo',
  [BrazilStates.Sergipe]: 'Sergipe',
  [BrazilStates.Tocantins]: 'Tocantins'
};
